#!/bin/bash
set -e

SENSU_SERVICE=${SENSU_SERVICE-$1}

case "$SENSU_SERVICE" in
  api|server|client)
    shopt -s nullglob #fixes null glob when no file exists
    for file in $CONFIG_DIR/*.tmpl
    do
      echo "Processing $file file..."
      dockerize -template $file:${file%.*} echo
    done

    command="sensu-$SENSU_SERVICE -c $CONFIG_FILE -d $CONFIG_DIR -e $EXTENSION_DIR -L $LOG_LEVEL $OPTIONS"
    dockerize -template /etc/sensu/config.json.tmpl:/etc/sensu/config.json $command
    ;;
  *)
    echo 'Specify either api/server/client'
    exit 1
    ;;
esac